language: python
python: 
     - 3.7
     - 3.6
before_install:
     - sudo apt-get update
     - sudo apt-get -y dist-upgrade
     - sudo apt-get -y install nmap

provider: script
install: pip3 install --upgrade pip
script: sudo ./deeper 149.28.164.223 -z 10 -tt

