before_install: 
  - "sudo apt-get update"
  - "sudo apt-get -y install nmap"
dist: xenial
install: 
  - "pip3 install --upgrade pip"
language: python
provider: script
python: 
  - "3.7.1"
  - "3.6.7"
script: "python3 ./deeper 127.0.0.1"
